-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clients
(
    id bigint NOT NULL,
    contact contact NOT NULL,
    name bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.comment
(
    id bigint NOT NULL,
    description text NOT NULL,
    resolved boolean NOT NULL,
    "typeId" bigint NOT NULL,
    "clienteId" bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.type
(
    id bigint NOT NULL,
    "commentType" text NOT NULL,
    priority smallint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."assistLog"
(
    id bigint NOT NULL,
    "postDate" date NOT NULL,
    "resolveDate" date,
    "commentId" bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.comment
    ADD FOREIGN KEY ("clienteId")
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comment
    ADD FOREIGN KEY ("typeId")
    REFERENCES public.type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."assistLog"
    ADD FOREIGN KEY ("commentId")
    REFERENCES public.comment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;