-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."assistLog"
(
    id bigint NOT NULL,
    "postDate" date NOT NULL,
    "resolveDate" date,
    "commentId" bigint NOT NULL,
    CONSTRAINT "assistLog_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    contact contact,
    name text COLLATE pg_catalog."default",
    CONSTRAINT clients_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.comment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description text COLLATE pg_catalog."default" NOT NULL,
    resolved boolean NOT NULL,
    "typeId" bigint NOT NULL,
    "clienteId" bigint NOT NULL,
    "ordenID" integer,
    date date NOT NULL,
    CONSTRAINT comment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.type
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "commentType" text COLLATE pg_catalog."default" NOT NULL,
    priority smallint NOT NULL,
    CONSTRAINT type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description text COLLATE pg_catalog."default" NOT NULL,
    "clientId" bigint NOT NULL,
    date date NOT NULL,
    total numeric NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);
END;